// SPDX-License-Identifier: MIT
// PLL: 25 MHz → 125 MHz (0°) + 125 MHz (90°)
//
// Generated by:
//   ecppll --clkin 25 --clkout0 125 --clkout1 125 --phase1 90
//
// PLL math:
//   f_REF  = 25 MHz / CLKI_DIV(1)               = 25 MHz
//   f_VCO  = f_REF × CLKFB_DIV(5) × CLKOP_DIV(5) = 625 MHz   (in 400-800 MHz range)
//   CLKOP  = f_VCO / CLKOP_DIV(5)                = 125 MHz at 0°
//   CLKOS  = f_VCO / CLKOS_DIV(5)                = 125 MHz at 90°
//
// 90° phase shift on CLKOS:
//   At 125 MHz, full period = 8 ns; 90° = 2 ns.
//   VCO period = 1.6 ns; CPHASE step = 1 VCO period; FPHASE step = 0.2 ns (1/8 VCO).
//   2 ns = 1 × 1.6 ns + 2 × 0.2 ns → CLKOS_CPHASE = CLKOP_CPHASE + 1, CLKOS_FPHASE = 2.
//
// `define SIM_PLL` for Verilator/Icarus behavioral simulation.

module pll_25_to_125 (
    input  wire clkin,
    output wire clkout0,    // 125 MHz, 0°
    output wire clkout1,    // 125 MHz, 90° (for RGMII GTXCLK)
    output wire locked
);

`ifdef SIM_PLL
    // ---- Behavioral model for simulation ----
    reg c0 = 0;
    reg c1 = 0;
    always #4 c0 = ~c0;
    initial begin
        #2;
        forever #4 c1 = ~c1;
    end
    assign clkout0 = c0;
    assign clkout1 = c1;
    assign locked  = 1'b1;
`else
    // ---- Real ECP5 PLL primitive ----
    wire clkop_int;
    wire clkos_int;

    (* FREQUENCY_PIN_CLKI    = "25"  *)
    (* FREQUENCY_PIN_CLKOP   = "125" *)
    (* FREQUENCY_PIN_CLKOS   = "125" *)
    (* ICP_CURRENT           = "12"  *)
    (* LPF_RESISTOR          = "8"   *)
    (* MFG_ENABLE_FILTEROPAMP = "1"  *)
    (* MFG_GMCREF_SEL        = "2"   *)
    EHXPLLL #(
        .PLLRST_ENA      ("DISABLED"),
        .INTFB_WAKE      ("DISABLED"),
        .STDBY_ENABLE    ("DISABLED"),
        .DPHASE_SOURCE   ("DISABLED"),
        .OUTDIVIDER_MUXA ("DIVA"),
        .OUTDIVIDER_MUXB ("DIVB"),
        .OUTDIVIDER_MUXC ("DIVC"),
        .OUTDIVIDER_MUXD ("DIVD"),
        .CLKI_DIV        (1),
        .CLKFB_DIV       (5),
        .CLKOP_ENABLE    ("ENABLED"),
        .CLKOP_DIV       (5),
        .CLKOP_CPHASE    (2),
        .CLKOP_FPHASE    (0),
        .CLKOS_ENABLE    ("ENABLED"),
        .CLKOS_DIV       (5),
        .CLKOS_CPHASE    (3),    // +1 VCO period vs CLKOP
        .CLKOS_FPHASE    (2),    // +2 fine units (0.4 ns)
        .FEEDBK_PATH     ("CLKOP")
    ) u_pll (
        .RST         (1'b0),
        .STDBY       (1'b0),
        .CLKI        (clkin),
        .CLKFB       (clkop_int),
        .PHASESEL0   (1'b0),
        .PHASESEL1   (1'b0),
        .PHASEDIR    (1'b1),
        .PHASESTEP   (1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC (1'b0),
        .ENCLKOP     (1'b0),
        .CLKOP       (clkop_int),
        .CLKOS       (clkos_int),
        .LOCK        (locked)
    );

    assign clkout0 = clkop_int;
    assign clkout1 = clkos_int;
`endif

endmodule
