// SPDX-License-Identifier: MIT
// Embedded WebUI: a single self-contained HTML page served at "/".
// Vanilla JS, no external dependencies. Polls /api/status at 1 Hz,
// loads /api/config on demand, lets the user POST changes back, and
// streams /audio.wav for live channel preview.

#include "web_index.h"
#include "httpd_lite.h"

const char web_index_html[] =
"<!doctype html><html lang=en><head><meta charset=utf-8>"
"<title>AES67 Bridge</title>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<style>"
"*{box-sizing:border-box;font-family:-apple-system,Segoe UI,Helvetica,sans-serif}"
"body{background:#0f1216;color:#dce3ee;margin:0;padding:0;font-size:14px}"
"header{background:#181d24;border-bottom:1px solid #2a313b;padding:14px 20px;display:flex;align-items:center;gap:18px}"
"header h1{margin:0;font-size:18px;color:#fa3}"
"header .pill{background:#222932;border:1px solid #2a313b;border-radius:99px;padding:3px 10px;font-size:12px;color:#9aa6b5}"
"header .ok{color:#7c5}"
"header .warn{color:#fa3}"
"header .err{color:#e66}"
"main{display:grid;grid-template-columns:1fr 1fr;gap:18px;padding:18px;max-width:1400px;margin:0 auto}"
"section{background:#161b22;border:1px solid #232a33;border-radius:8px;padding:16px}"
"section h2{margin:0 0 12px;font-size:14px;color:#fa3;text-transform:uppercase;letter-spacing:.5px}"
"table{width:100%;border-collapse:collapse}"
"td{padding:5px 0;font-size:13px}"
"td:first-child{color:#8b95a5;width:45%}"
"td:last-child{color:#dce3ee;font-weight:500;font-family:ui-monospace,monospace}"
"input[type=text],input[type=number],select{background:#0d1117;border:1px solid #2a313b;color:#dce3ee;padding:5px 8px;border-radius:4px;font-family:ui-monospace,monospace;width:100%;font-size:12px}"
"button{background:#fa3;color:#0f1216;border:0;padding:7px 14px;border-radius:4px;font-weight:600;cursor:pointer;font-size:13px}"
"button:hover{background:#fb5}"
"button.alt{background:#2a313b;color:#dce3ee}"
"button.alt:hover{background:#3a414b}"
".form{display:grid;grid-template-columns:1fr 1.5fr;gap:8px 12px;align-items:center}"
".form label{color:#8b95a5;font-size:12px}"
".meter{height:8px;background:#0d1117;border-radius:4px;overflow:hidden;margin-top:3px}"
".meter>span{display:block;height:100%;background:linear-gradient(90deg,#7c5,#fa3,#e66);width:0%;transition:width .1s}"
".chrow{display:grid;grid-template-columns:30px 1fr 60px 30px;gap:8px;align-items:center;padding:6px 0;border-bottom:1px solid #1d242d}"
".chrow:last-child{border-bottom:0}"
".chnum{color:#8b95a5;font-family:ui-monospace,monospace;font-size:11px}"
".chrow input[type=range]{width:100%}"
".grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}"
"audio{width:100%;margin-top:10px}"
"footer{text-align:center;padding:20px;color:#5a6473;font-size:11px}"
".eqgrid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:8px;opacity:.6}"
".eqgrid .knob{background:#0d1117;border:1px solid #2a313b;border-radius:6px;padding:8px;text-align:center;font-size:11px}"
".eqgrid .knob b{display:block;color:#fa3;font-size:14px;margin-bottom:2px}"
"</style></head><body>"
"<header>"
"<h1>AES67 Bridge</h1>"
"<span class=pill id=hostname>aes67br-...</span>"
"<span class=pill id=ip>0.0.0.0</span>"
"<span class=pill id=role>...</span>"
"<span class=pill id=state>...</span>"
"</header>"
"<main>"

"<section><h2>Live Stats</h2>"
"<table>"
"<tr><td>PTP role</td><td id=s_role>-</td></tr>"
"<tr><td>PTP state</td><td id=s_state>-</td></tr>"
"<tr><td>PTP time</td><td id=s_time>-</td></tr>"
"<tr><td>Offset (ns)</td><td id=s_offset>-</td></tr>"
"<tr><td>Path delay (ns)</td><td id=s_delay>-</td></tr>"
"<tr><td>Sync count</td><td id=s_sync>-</td></tr>"
"<tr><td>RTP RX</td><td id=s_rx>-</td></tr>"
"<tr><td>RTP TX</td><td id=s_tx>-</td></tr>"
"<tr><td>Seq errors</td><td id=s_seq>-</td></tr>"
"<tr><td>Jitter buffer</td><td id=s_jbuf>-</td></tr>"
"</table></section>"

"<section><h2>Configuration</h2>"
"<div class=form>"
"<label>Sample rate</label><select id=c_sr><option>44100<option>48000<option>96000</select>"
"<label>Channels</label><select id=c_ch><option>1<option>2<option>4<option>8</select>"
"<label>Samples / packet</label><input id=c_spp type=number min=1 max=1024>"
"<label>Jitter buffer (frames)</label><input id=c_jbd type=number min=1 max=512>"
"<label>RTP port</label><input id=c_port type=number>"
"<label>Payload type</label><input id=c_pt type=number>"
"<label>PTP role</label><select id=c_master><option value=0>Slave (BMC)<option value=1>Master (force)</select>"
"<label>TX delay (ns)</label><input id=c_txd type=number>"
"<label>RX delay (ns)</label><input id=c_rxd type=number>"
"<label>Servo Kp (Q16.16)</label><input id=c_kp type=number>"
"<label>Servo Ki (Q16.16)</label><input id=c_ki type=number>"
"</div>"
"<p style=margin-top:14px><button onclick=loadConfig()>Reload</button> "
"<button onclick=saveConfig()>Apply</button></p>"
"</section>"

"<section><h2>Channel Preview</h2>"
"<div class=grid2>"
"<div><label style='color:#8b95a5;font-size:12px'>Left channel</label>"
"<select id=p_left></select></div>"
"<div><label style='color:#8b95a5;font-size:12px'>Right channel</label>"
"<select id=p_right></select></div>"
"</div>"
"<p style=margin-top:10px><button onclick=startPreview()>Listen</button> "
"<button class=alt onclick=stopPreview()>Stop</button></p>"
"<audio id=preview controls></audio>"
"<p style='font-size:11px;color:#5a6473;margin-top:8px'>Live preview of the RTP stream after the DSP slot. ~5 ms HW capture FIFO + browser audio element buffering.</p>"
"</section>"

"<section><h2>DSP - Gain / Mute / Meter</h2>"
"<div id=dsp></div>"
"<p style=margin-top:14px><b style='color:#fa3'>Future:</b> per-channel biquad EQ</p>"
"<div class=eqgrid>"
"<div class=knob><b>80Hz</b>0 dB</div>"
"<div class=knob><b>250Hz</b>0 dB</div>"
"<div class=knob><b>1kHz</b>0 dB</div>"
"<div class=knob><b>4kHz</b>0 dB</div>"
"<div class=knob><b>12kHz</b>0 dB</div>"
"</div>"
"</section>"

"<section><h2>SAP / SDP Sessions</h2>"
"<div id=sap>(none)</div>"
"</section>"

"<section><h2>About</h2>"
"<table>"
"<tr><td>Hostname</td><td id=i_hostname>-</td></tr>"
"<tr><td>MAC</td><td id=i_mac>-</td></tr>"
"<tr><td>IP</td><td id=i_ip>-</td></tr>"
"<tr><td>Build</td><td id=i_build>-</td></tr>"
"</table></section>"

"</main>"
"<footer>AES67 Bridge on Colorlight i9 v7.2 - PTP+RTP+TDM hardware engine + lwIP/VexRiscv management</footer>"

"<script>"
"async function getJ(u){return (await fetch(u)).json()}"
"async function postJ(u,b){return (await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)})).json()}"
"function $(id){return document.getElementById(id)}"

"async function loadInfo(){let i=await getJ('/api/info');"
"  $('hostname').textContent=i.hostname;$('i_hostname').textContent=i.hostname;"
"  $('ip').textContent=i.ip;$('i_ip').textContent=i.ip;"
"  $('i_mac').textContent=i.mac;$('i_build').textContent=i.build}"

"async function loadStatus(){try{let s=await getJ('/api/status');"
"  $('s_role').textContent=s.ptp.role;$('role').textContent=s.ptp.role;$('role').className='pill '+(s.ptp.role==='MASTER'||s.ptp.role==='SLAVE'?'ok':'warn');"
"  $('s_state').textContent=s.ptp.state;$('state').textContent=s.ptp.state;$('state').className='pill '+(s.ptp.state==='LOCKED'?'ok':(s.ptp.state==='LOCKING'?'warn':'err'));"
"  $('s_time').textContent=s.ptp.sec+'.'+String(s.ptp.nsec).padStart(9,'0');"
"  $('s_offset').textContent=s.ptp.offset_ns;$('s_delay').textContent=s.ptp.path_delay_ns;"
"  $('s_sync').textContent=s.ptp.sync_count;"
"  $('s_rx').textContent=s.rtp.rx;$('s_tx').textContent=s.rtp.tx;"
"  $('s_seq').textContent=s.rtp.seq_errors;$('s_jbuf').textContent=s.rtp.jbuf_depth;}catch(e){}}"

"async function loadConfig(){let c=await getJ('/api/config');"
"  $('c_sr').value=c.sample_rate;$('c_ch').value=c.num_channels;"
"  $('c_spp').value=c.samples_per_packet;$('c_jbd').value=c.jbuf_target_depth;"
"  $('c_port').value=c.rtp_port;$('c_pt').value=c.payload_type;"
"  $('c_master').value=c.mode_is_master;$('c_txd').value=c.tx_delay_ns;"
"  $('c_rxd').value=c.rx_delay_ns;$('c_kp').value=c.kp;$('c_ki').value=c.ki}"

"async function saveConfig(){await postJ('/api/config',{"
"  sample_rate:+$('c_sr').value,num_channels:+$('c_ch').value,"
"  samples_per_packet:+$('c_spp').value,jbuf_target_depth:+$('c_jbd').value,"
"  rtp_port:+$('c_port').value,payload_type:+$('c_pt').value,"
"  mode_is_master:+$('c_master').value,tx_delay_ns:+$('c_txd').value,"
"  rx_delay_ns:+$('c_rxd').value,kp:+$('c_kp').value,ki:+$('c_ki').value});"
"  loadConfig()}"

"async function loadDsp(){let d=await getJ('/api/dsp');"
"  let h='';for(let i=0;i<16;i++){let c=d.channels[i];"
"    let pk=Math.min(100,(c.peak/8388608)*100);"
"    h+='<div class=chrow><span class=chnum>'+i+'</span>'+"
"       '<input type=range min=0 max=2147483647 value='+c.gain+' onchange=setGain('+i+',this.value)>'+"
"       '<div><div class=meter><span style=\"width:'+pk+'%\"></span></div></div>'+"
"       '<input type=checkbox '+(c.mute?'checked':'')+' onchange=setMute('+i+',this.checked?1:0)></div>'}"
"  $('dsp').innerHTML=h}"
"async function setGain(ch,v){await postJ('/api/dsp',{ch:ch,gain:+v})}"
"async function setMute(ch,v){await postJ('/api/dsp',{ch:ch,mute:v})}"

"async function loadSap(){let s=await getJ('/api/sap');"
"  $('sap').innerHTML=s.count?s.sessions.map(x=>'<div>id '+x.id+' ('+x.sdp_len+' bytes)</div>').join(''):'(none)'}"

"function fillCh(){let opts='';for(let i=0;i<16;i++)opts+='<option value='+i+'>Channel '+i+'</option>';"
"  $('p_left').innerHTML=opts;$('p_right').innerHTML=opts;$('p_right').value=1}"

"function startPreview(){let l=$('p_left').value,r=$('p_right').value;"
"  $('preview').src='/audio.wav?l='+l+'&r='+r+'&t='+Date.now();$('preview').play()}"
"function stopPreview(){$('preview').pause();$('preview').src=''}"

"fillCh();loadInfo();loadStatus();loadConfig();loadDsp();loadSap();"
"setInterval(loadStatus,1000);setInterval(loadDsp,500);setInterval(loadSap,5000);"
"</script></body></html>";

static void index_handler(httpd_conn_t *c, http_method_t m, const char *p,
                          const char *q, const uint8_t *b, size_t bl)
{
    (void)m; (void)p; (void)q; (void)b; (void)bl;
    httpd_send_text(c, 200, "text/html; charset=utf-8", web_index_html);
}

void web_index_register(void)
{
    httpd_lite_route("/", index_handler);
}
